# Generated by Django 4.2.20 on 2025-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JaundiceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('ethnicity', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('jaundiced', 'Jaundiced'), ('normal', 'Normal')], max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('feeding_pattern', models.CharField(blank=True, max_length=100)),
                ('sleeping_pattern', models.CharField(blank=True, max_length=100)),
                ('stooling_pattern', models.CharField(blank=True, max_length=100)),
                ('urine_color', models.CharField(blank=True, max_length=100)),
                ('skin_color', models.CharField(blank=True, max_length=100)),
                ('eye_color', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
