# Generated by Django 4.2.20 on 2025-06-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_jaundicecase_file_path_jaundicecase_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jaundicecase',
            name='image',
        ),
        migrations.AddField(
            model_name='jaundicecase',
            name='file_path',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
