# Generated by Django 4.2.20 on 2025-06-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_jaundicecase_image_jaundicecase_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaundicecase',
            name='condition',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jaundicecase',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
    ]
