# Generated by Django 4.2.20 on 2025-06-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_jaundicecase_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jaundicecase',
            name='file_path',
        ),
        migrations.AddField(
            model_name='jaundicecase',
            name='image',
            field=models.ImageField(default=1, upload_to='jaundice_dataset/'),
            preserve_default=False,
        ),
    ]
